// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { normalizeDatabaseUrl } from "./src/database-url";

const databaseUrl = normalizeDatabaseUrl(process.env.DATABASE_URL);

if (!databaseUrl) {
  throw new Error("DATABASE_URL is missing. Set it in backend/.env before running Prisma commands.");
}

const protocol = new URL(databaseUrl).protocol;
if (!protocol.startsWith("postgres")) {
  throw new Error(
    `DATABASE_URL must use a PostgreSQL connection string. Received: ${databaseUrl}`,
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx ts-node ./prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
